## Project information
site_name: DFA - Archivio testi
site_url: https://unict-dmi.github.io/DFA-compiti/
site_description: Compiti scritti del Dipartimento di Fisica e Astronomia dell'Università degli Studi di Catania

## Repository
repo_name: DFA-compiti
repo_url: https://github.com/unict-dmi/DFA-compiti
edit_uri: edit/main/docs/ #disables edit button

## Copyright
copyright: Licenza CC-BY-SA-4.0

## Social Media e Analytics
extra:
  analytics:
    provider: google
    property: G-VKFNKR4L49
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: google
    actions:
      - accept
      - reject
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UNICT-DMI/DFA-compiti
      name: GitHub
    - icon: fontawesome/solid/rss
      link: ./feed_rss_created.xml
      name: Feed RSS



## Configuration
theme:
  name: material
  custom_dir: overrides
  language: it
  font:
    text: Mulish
  features:
    - navigation.top
    - navigation.footer
    - content.action.edit
    - navigation.tabs
    - navigation.indexes

  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/git-alt
    logo: material/file-document-edit-outline

  favicon: assets/logo-circle.png

plugins:
  - include-markdown
  - tags:
      tags_file: docenti.md
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - search:
        lang: it
#  - rss:
#     abstract_chars_count: 160
#     date_from_meta:
#        as_creation: "date"
#        as_update: false
#        datetime_format: "%d-%m-%Y"
     # datetime_format: "%Y-%m-%d"
#     image:
#     feed_ttl: 1440
#     length: 20
#     pretty_print: false
#     match_path: ".*"
#     url_parameters:
#        utm_source: "documentation"
#        utm_medium: "RSS"
#        utm_campaign: "feed-syndication"

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
          permalink: ↵
  - meta
  - md_in_html
  - mkdocs-click
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed
  - pymdownx.critic:
        mode: view
  - pymdownx.betterem:
        smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
        clickable_checkbox: true
  - attr_list
  - def_list
  - abbr
  - pymdownx.snippets
  - footnotes
  - tables
  - pymdownx.arithmatex:
        generic: true

## Custom theme additions
extra_javascript:
   - javascript/extra.js
   - https://unpkg.com/mermaid/dist/mermaid.min.js
   - javascripts/mathjax.js
   - https://polyfill.io/v3/polyfill.min.js?features=es6
   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Foglio di stile personalizzato
extra_css:
   - stylesheets/extra.css


## Page tree
nav:
   - Home: index.md
   - Primo anno:
      - Home: cursus/primo-anno.md
      - Fisica Generale 1:
         - fisica-1/index.md
         - 2010:
            - fisica-1/2010/2010-02-10.md
            - fisica-1/2010/2010-02-24.md
            - fisica-1/2010/2010-06-29.md
            - fisica-1/2010/2010-07-14.md
            - fisica-1/2010/2010-09-09.md
            - fisica-1/2010/2010-09-28.md
         - 2011:
            - fisica-1/2011/2011-01-27.md
            - fisica-1/2011/2011-02-08.md
            - fisica-1/2011/2011-02-28.md
            - fisica-1/2011/2011-06-29.md
            - fisica-1/2011/2011-07-13.md
            - fisica-1/2011/2011-09-14.md
            - fisica-1/2011/2011-10-05.md
            - fisica-1/2011/2011-12-19.md
         - 2012:
            - fisica-1/2012/2012-02-08.md
            - fisica-1/2012/2012-02-29.md
            - fisica-1/2012/2012-06-27.md
            - fisica-1/2012/2012-09-12.md
            - fisica-1/2012/2012-12-19.md
         - 2013:
            - fisica-1/2013/2013-02-13.md
            - fisica-1/2013/2013-02-27.md
            - fisica-1/2013/2013-06-26.md
            - fisica-1/2013/2013-07-10.md
            - fisica-1/2013/2013-09-11.md
         - 2014:
            - fisica-1/2014/2014-02-12.md
            - fisica-1/2014/2014-02-26.md
            - fisica-1/2014/2014-06-25.md
            - fisica-1/2014/2014-07-09.md
            - fisica-1/2014/2014-09-10.md
         - 2015:
            - fisica-1/2015/2015-02-11.md
            - fisica-1/2015/2015-02-26.md
            - fisica-1/2015/2015-06-24.md
            - fisica-1/2015/2015-07-08.md
            - fisica-1/2015/2015-09-09.md
            - fisica-1/2015/2015-12-16.md
         - 2016:
            - fisica-1/2016/2016-02-10.md
            - fisica-1/2016/2016-06-22.md
            - fisica-1/2016/2016-07-06.md
            - fisica-1/2016/2016-09-07.md
            - fisica-1/2016/2016-12-14.md
         - 2017:
            - fisica-1/2017/2017-02-08.md
            - fisica-1/2017/2017-02-22.md
            - fisica-1/2017/2017-06-21.md
            - fisica-1/2017/2017-07-05.md
            - fisica-1/2017/2017-09-06.md
            - fisica-1/2017/2017-12-13.md
         - 2018:
            - fisica-1/2018/2018-02-07.md
            - fisica-1/2018/2018-02-21.md
            - fisica-1/2018/2018-06-20.md
            - fisica-1/2018/2018-07-04.md
            - fisica-1/2018/2018-09-05.md
            - fisica-1/2018/2018-12-12.md
         - 2019:
            - fisica-1/2019/2019-02-13.md
            - fisica-1/2019/2019-02-27.md
            - fisica-1/2019/2019-06-19.md
            - fisica-1/2019/2019-07-03.md
            - fisica-1/2019/2019-09-11.md
            - fisica-1/2019/2019-09-25.md
            - fisica-1/2019/2019-12-11.md
         - 2020:
            - fisica-1/2020/2020-02-12.md
            - fisica-1/2020/2020-02-26.md
            - fisica-1/2020/2020-06-17.md
            - fisica-1/2020/2020-07-08.md
            - fisica-1/2020/2020-09-01.md
            - fisica-1/2020/2020-09-16.md
            - fisica-1/2020/2020-12-23.md
         - 2021:
            - fisica-1/2021/2021-02-03.md
            - fisica-1/2021/2021-02-17.md
            - fisica-1/2021/2021-03-31.md
            - fisica-1/2021/2021-06-23.md
            - fisica-1/2021/2021-07-14.md
            - fisica-1/2021/2021-09-01.md
            - fisica-1/2021/2021-12-23.md
         - 2022:
            - fisica-1/2022/2022-02-02.md
            - fisica-1/2022/2022-02-16.md
            - fisica-1/2022/2022-06-22.md
            - fisica-1/2022/2022-07-13.md
            - fisica-1/2022/2022-09-07.md
            - fisica-1/2022/2022-09-22.md
         - 2023:
            - fisica-1/2023/2023-01-13.md
            - fisica-1/2023/2023-01-30.md
            - fisica-1/2023/2023-02-01.md
      - Geometria:
         - geometria/index.md
         - 2021:
            - geometria/2021-07-09.md
            - geometria/2021-09-09.md
            - geometria/2021-09-24.md
         - 2022:
            - geometria/2022-01-28.md
            - geometria/2022-02-25.md
            - geometria/2022-11-25.md
         - 2023:
            - geometria/2023-04-05.md
   - Secondo anno:
      - Home: cursus/secondo-anno.md
      - Fisica Generale 2:
         - fisica-2/index.md
         - 2023:
            - fisica-2/2023-07-12-completa.md
            - fisica-2/2023-07-12-itinere.md
            - fisica-2/2023-09-06-completa.md
            - fisica-2/2023-09-06-itinere.md
            - fisica-2/2023-09-20-itinere.md
      - Meccanica analitica:
         - meccanica-analitica/index.md
         - 2013:
            - meccanica-analitica/2013-06-13.md
            - meccanica-analitica/2013-06-24.md
            - meccanica-analitica/2013-11-20.md
         - 2014:
            - meccanica-analitica/2014-03-03.md
            - meccanica-analitica/2014-05-19.md
            - meccanica-analitica/2014-06-27.md
            - meccanica-analitica/2014-07-18.md
            - meccanica-analitica/2014-09-12.md
            - meccanica-analitica/2014-10-03.md
            - meccanica-analitica/2014-11-06.md
         - 2015:
            - meccanica-analitica/2015-12-11.md
            - meccanica-analitica/2015-12-14.md
         - 2016:
            - meccanica-analitica/2016-02-11.md
            - meccanica-analitica/2016-02-12.md
            - meccanica-analitica/2016-03-04.md
            - meccanica-analitica/2016-04-20.md
            - meccanica-analitica/2016-04-29.md
            - meccanica-analitica/2016-05-06.md
         - 2019:
            - meccanica-analitica/2019-03-01.md
         - 2020:
            - meccanica-analitica/2020-02-28.md
            - meccanica-analitica/2020-07-17.md
            - meccanica-analitica/2020-09-25.md
         - 2021:
            - meccanica-analitica/2021-02-26.md
            - meccanica-analitica/2021-06-18.md
            - meccanica-analitica/2021-07-16.md
            - meccanica-analitica/2021-09-10.md
            - meccanica-analitica/2021-09-24.md
            - meccanica-analitica/2021-12-23.md
         - 2022:
            - meccanica-analitica/2022-02-04.md
            - meccanica-analitica/2022-02-25.md
            - meccanica-analitica/2022-04-15.md
            - meccanica-analitica/2022-06-24.md
            - meccanica-analitica/2022-07-22.md
            - meccanica-analitica/2022-09-02.md
         - 2023:
            - meccanica-analitica/2023-02-10.md
      - Informatica e laboratorio:
         - informatica/index.md
   - Note:
      - note.md
